version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/postgres:10.5
    environment:
      DATABASE_URL: postgres://postgres:@localhost/circle_test
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: installing dependencies
          command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements/local.txt
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest

workflows:
  main:
    jobs:
      - build-and-test
