version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
      - image: cimg/postgres:14.2.0
    environment:
      DATABASE_URL: postgres://postgres:@localhost/circle_test
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: v001-app-{{ .Branch }}-{{ checksum "requirements/local.txt" }}
      - run:
          name: installing dependencies
          command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements/local.txt
      - save_cache:
          key: v001-app-{{ .Branch }}-{{ checksum "requirements/local.txt" }}
          paths:
            - 'venv'
      - run:
          name: Add python project to path
          command: 'echo "$(realpath .)/app" > venv/lib/python3.10/site-packages/app.pth'
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest

workflows:
  main:
    jobs:
      - build-and-test
